### ISSUE TITLE
on your webpage... maybe rewrite that the quickest is now Python-3.11

### ISSUE THREAD

**Issue by stonebig** [pypyodbc/pypyodbc#20]
![image](https://user-images.githubusercontent.com/4312421/215269539-264d1f7e-7f23-477f-ba04-9c5cfb0cb16c.png)

**Comment by rolweber** [comment]
1. Where does that screenshot come from?
2. What do you consider our webpage?

pypyodbc is effectively abandoned. I'm not going to update the documentation, and the only other person with write access to this repo hasn't posted in over a year, afaik. PRs are welcome, though. I can still review and merge, though I don't have full access to the repo and org.

**Comment by stonebig** [comment]
Ah, ok
