### ISSUE TITLE
Improve pypyobdc library

### ISSUE THREAD

**Issue by lilymillerr** [pypyodbc/pypyodbc#24]
Hi Sir,

✅ You said that "Fix a bug on the pypyodbc library linked to HFSQL database. When a line contains an empty value (''), the value of the previous line is used." and we can do it with very high quality and fast. You can check our strong portfolio to make sure.

📩 Would you like me to send you the portfolio?

Thanks,
- Lily.

**Comment by rolweber** [comment]
Spam
