### ISSUE TITLE
Python 3 SQLAlchemy compatibility

### ISSUE THREAD

**Issue by skazazes-work** [pypyodbc/pypyodbc#7]
Currently it seems there are some features of pypyodbc that do not return the results SQLAlchemy is expecting, specifically when used in conjuncture with Pandas.

At the moment it appears that pypyodbc is not populating the .description attribute of results returned from SQLAlchemy's .execute() function properly. As a result when using pandas.read_sql_query() passing a preconfigured SQLAlchemy connection that is using pypyodbc, the column names are not what they are in the database.

**Comment by chrisimcevoy** [comment]
See #4
